// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig, env } from "prisma/config";

// Load .env.local first with override to ensure it takes precedence
// This ensures the Neon database connection string from .env.local
// overrides any DATABASE_URL in .env (which points to localhost)
config({ path: ".env.local", override: true });
// Load .env as fallback (but .env.local values take precedence)
config({ path: ".env" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
